volumes:
  open_webui_storage:
  ollama_storage:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    networks:
      - open-webui
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - open_webui_storage:/app/backend/data
    container_name: open-webui
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - open-webui
    volumes:
      - ollama_storage:/root/.ollama

  ollama-pull-llama:
    image: ollama/ollama:latest
    networks:
      - open-webui
    environment:
      - OLLAMA_HOST=http://ollama:11434
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 3; ollama pull deepseek-r1:7b"
    depends_on:
      - ollama

networks:
  open-webui:
